CREATE OR REPLACE FUNCTION nthhighestsalary(N INT) RETURNS INT AS $$
    SELECT DISTINCT salary
    FROM Employee
    ORDER BY salary DESC
    LIMIT CASE WHEN N > 0 THEN 1 ELSE 0 END OFFSET GREATEST(N - 1, 0);
$$ LANGUAGE SQL;
