name: verification

on:
  push:

jobs:
  verification:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
